const mockFirebase = {
  user: {
    uid: 'CnubZiTNYjZR7aG6Myp14f68B7p1',
  },
  cardArray: [
    {
      id: 1,
      adjustedSalary: 75000,
      company: 'Google',
      title: 'Director of Underwater Basket Weaving',
      city: 'Denver',
      state: 'CO',
      salary: 65000,
      bonus: 10000,
      retirement: 0.07,
      insurance: 200,
      distance: 5,
      beer: true,
      lunch: true,
    },
    {
      id: 2,
      adjustedSalary: 75000,
      company: 'Facebook',
      title: 'Director of Underwater Basket Weaving',
      city: 'Denver',
      state: 'CO',
      salary: 65000,
      bonus: 10000,
      retirement: 0.07,
      insurance: 200,
      distance: 5,
      beer: true,
      lunch: true,
    },
    {
      id: 3,
      adjustedSalary: 75000,
      company: 'SnapChat',
      title: 'Director of Underwater Basket Weaving',
      city: 'Denver',
      state: 'CO',
      salary: 65000,
      bonus: 10000,
      retirement: 0.07,
      insurance: 200,
      distance: 5,
      beer: true,
      lunch: true,
    },
  ],
}

module.exports = mockFirebase
